-- MySQL Script generated by MySQL Workbench
-- Fri Jan 27 13:49:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shopping_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopping_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping_db` DEFAULT CHARACTER SET utf8 ;
USE `shopping_db` ;

-- -----------------------------------------------------
-- Table `shopping_db`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Products` (
  `Product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `img_adress` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT(11) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `manufacturer` VARCHAR(45) NULL DEFAULT NULL,
  `radius` VARCHAR(45) NULL DEFAULT NULL,
  `units_sold` INT(11) NULL DEFAULT '0',
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `rpm` INT(11) NULL DEFAULT NULL,
  `effect` INT(11) NULL DEFAULT NULL,
  `sound` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shopping_db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Users` (
  `User_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `account_create_time` DATE NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `permission` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shopping_db`.`Basket_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Basket_Items` (
  `Users_User_id` INT(11) NOT NULL,
  `Products_Product_id` INT(11) NOT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Users_User_id`, `Products_Product_id`),
  FOREIGN KEY (`Products_Product_id`)
    REFERENCES `shopping_db`.`Products` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`Users_User_id`)
    REFERENCES `shopping_db`.`Users` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shopping_db`.`Order_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_db`.`Order_History` (
  `Order_id` INT(11) NOT NULL,
  `Products_Product_id` INT(11) NOT NULL,
  `Users_User_id` INT(11) NOT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `timestamp` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Order_id`),
  FOREIGN KEY (`Products_Product_id`)
    REFERENCES `shopping_db`.`Products` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  FOREIGN KEY (`Users_User_id`)
    REFERENCES `shopping_db`.`Users` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;